### ISSUE TITLE
Improvement: The size animates but fade doesn't when changing from the larger widget to smaller one.

### ISSUE THREAD

**Issue by yasinarik** [marcglasberg/animated_size_and_fade#1]
First of all, I **LOVE** the packages you wrote. They are like the SwissTool of Flutter.

I might suggest an idea, without knowing if it's applicable. 

As also seen on the example gif you've provided, when the size expands, it animates eventually. However, when it shrinks, the smaller widget is applied to the state **immediately**. The size animates but fade doesn't when changing from the larger widget to smaller one.

So, it seems like the larger widget disappears immediately. How can I overcome this? Or can you please add that tiny little improvement? 

```
    return AnimatedSizeAndFade(
      fadeDuration: shrinkDuration,
      sizeDuration: shrinkDuration,
      sizeCurve: shrinkCurve,
      fadeInCurve: shrinkCurve,
      fadeOutCurve: shrinkCurve,
      vsync: this,
      child: shrink ? SizedBox(width: 0) : SomeCustomWidget(),
    );
```

**Comment by marcglasberg** [comment]
@yasinarik Thanks, I am glad you like my packages!

You can fade between them and change sizes, but you can play with the Curve and Duration to achieve different effects.

Try to modify the example so that the fade takes longer than the size change. Then the larger widget will take longer to disappear:

```
AnimatedSizeAndFade(
        child: toggle ? widget1 : widget2,
        fadeDuration: const Duration(milliseconds: 600),
        sizeDuration: const Duration(milliseconds: 300),
),
```

You can also play with `fadeInCurve` and `fadeOutCurve`.
